FROM postgres:15.3-alpine3.18 as db

ARG DB_NAME=mikes-db
ARG DB_USER=root
ARG DB_PASSWORD=change_it

ENV POSTGRES_DB=$DB_NAME
ENV POSTGRES_USER=$DB_USER
ENV POSTGRES_PASSWORD=$DB_PASSWORD

COPY src/main/resources/*.sql /docker-entrypoint-initdb.d/

EXPOSE 5432