apiVersion: v1
kind: Service
metadata:
  name: mikes-app
  labels:
    name: mikes-app
spec:
  selector:
    app: mikes-app
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mikes-app
  template:
    metadata:
      labels:
        app: mikes-app
    spec:
      containers:
        - name: mikes-app
          image: gaprado/mikes-app:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: db_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_password
